# Generated by Django 4.1.7 on 2023-03-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=16)),
                ("holder", models.CharField(max_length=100)),
                ("exp_date", models.DateField()),
                ("cvv", models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
