# Generated by Django 4.1.7 on 2023-03-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="brand",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
